### ISSUE TITLE
Gérer les propriétaires par nom+adresse

### ISSUE THREAD

**Issue by podybman** [northamerican/find-my-landlord#3]
Il y a plusieurs erreurs car les propriétaires sont regroupés par nom identique mais le Québec étant ce qu'il est, il y a de nombreux homonymes. Il conviendrait donc mieux d'identifier par couple nom et adresse (adresse au compte de taxe évidemment)

**Comment by northamerican** [comment]
Salut @podybman! Le problème devrait être régler maintenant (https://github.com/northamerican/find-my-landlord/commit/7ac0f575a4a5ce126d56143472d4367dfff98e8b). Contrairement au app original de Chicago qui avait un field pour identifier l'individu / contribuable, je voit pas tel chose dans les données de notre ville. Alors ca distingue pas entre M. Roy et M. Roy.

Pour régler, sa fait maintenant comme tu dit, mais en identifiant seulement par adresse. 

ex. 1234 quebec cie et 1235 quebec cie ont leur siège au 1000 clark suite 100, alors ils sont coupler. C'est pour ca il ne faut pas correspondre par nom du tout. Ceci est fait manuellement.

Le travail manuel fait est de trouver le vrai nom de la contribuable des entreprises. Pour ceux avec plus de cinq bâtiments, c'est fait. Avec les plus grands entreprises, de amples recherches sont fait, qui relie les entreprises avec plusieurs adresses.

exemple:
```
"Allied Properties REIT": [
  "134 PETER 1700",
  "1001 LENOIR B-376",
  "480 BOUL SAINT-LAURENT 600"
]
```
Ils ont plusieurs sièges sociales.

Un autre, qui règle des incohérences des données:
```
"226B SAINTE-ANNE",
"226 SAINTE-ANNE B"
```

En tout cas, clear ton cache et essaye le maintenant!

**Comment by podybman** [comment]
Super! Merci!
